#!/usr/bin/env python3
"""Migrate telemetry data from a local SQLite file into the configured storage backend.

Usage:
  - Ensure the Oracle wallet and ORACLE_* env vars are set (or oracle-config.json present).
  - If the container is running, you can copy the DB out with:
      docker cp ecopi-dashboard:/data/telemetry.db ./telemetry.db
  - Then run: .venv/bin/python migrate_sqlite_to_oracle.py

The script will normalize timestamps that contain only a time (HH:MM:SS) by
prepending the date 2026-06-08 as requested.
"""
import sqlite3
import os
from pathlib import Path
from datetime import datetime

from src.storage import get_storage


def normalize_timestamp(ts: str) -> str:
    """If ts contains only time (HH:MM or HH:MM:SS) prepend 2026-06-08.
    Otherwise return ts unchanged.
    """
    if not ts:
        return '2026-06-08 00:00:00'
    ts = ts.strip()
    # common forms: '13:10:00' or '13:10'
    try:
        if ':' in ts and ts.count('-') == 0:
            # treat as time only
            parts = ts.split()
            time_part = parts[-1]
            if time_part.count(':') in (1, 2):
                # ensure seconds
                if time_part.count(':') == 1:
                    time_part = time_part + ':00'
                return f'2026-06-08 {time_part}'
    except Exception:
        pass
    return ts


def migrate(sqlite_path: str):
    p = Path(sqlite_path)
    if not p.exists():
        print(f"SQLite DB not found at {sqlite_path}")
        return

    conn = sqlite3.connect(sqlite_path)
    cur = conn.cursor()

    try:
        cur.execute('SELECT id, timestamp, temperature, humidity, wind_speed, wind_dir, barometer, rain_rate, solar_rad, uv, ac_solar_w, house_power_w, net_balance FROM telemetry')
    except sqlite3.Error as e:
        print('Failed to read telemetry table from SQLite:', e)
        conn.close()
        return

    rows = cur.fetchall()
    print(f'Found {len(rows)} rows in SQLite telemetry table')

    storage = get_storage()

    # If storage exposes a low-level connection helper (OracleDB), use a
    # single connection and executemany to speed up the migration.
    use_bulk = hasattr(storage, '_connect')
    if use_bulk:
        print('Performing bulk migration using storage._connect()')
        conn_dest = storage._connect()
        if conn_dest is None:
            print('Failed to obtain destination DB connection from storage')
            conn.close()
            return

        cur_dest = conn_dest.cursor()
        # Ensure table exists (same DDL used by OracleDB.insert)
        try:
            cur_dest.execute("""
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE telemetry (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        timestamp VARCHAR2(64),
                        temperature NUMBER,
                        humidity NUMBER,
                        wind_speed NUMBER,
                        wind_dir NUMBER,
                        barometer NUMBER,
                        rain_rate NUMBER,
                        solar_rad NUMBER,
                        uv NUMBER,
                        ac_solar_w NUMBER,
                        house_power_w NUMBER,
                        net_balance NUMBER
                    )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN RAISE; END IF;
                END;
            """)
        except Exception:
            # ignore if DDL fails (may already exist)
            pass

        insert_sql = ("INSERT INTO telemetry (timestamp, temperature, humidity, wind_speed, wind_dir, "
                      "barometer, rain_rate, solar_rad, uv, ac_solar_w, house_power_w, net_balance) "
                      "VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12)")

        batch = []
        success = 0
        failed = 0
        BATCH_SIZE = 500

        for r in rows:
            _, ts, temperature, humidity, wind_speed, wind_dir, barometer, rain_rate, solar_rad, uv, ac_solar_w, house_power_w, net_balance = r
            ts_norm = normalize_timestamp(ts)
            params = [ts_norm, temperature, humidity, wind_speed, wind_dir, barometer, rain_rate, solar_rad, uv, ac_solar_w, house_power_w, net_balance]
            batch.append(params)
            if len(batch) >= BATCH_SIZE:
                try:
                    cur_dest.executemany(insert_sql, batch)
                    conn_dest.commit()
                    success += len(batch)
                except Exception as e:
                    print('Bulk insert failed for a batch:', e)
                    failed += len(batch)
                batch = []

        # final batch
        if batch:
            try:
                cur_dest.executemany(insert_sql, batch)
                conn_dest.commit()
                success += len(batch)
            except Exception as e:
                print('Bulk insert final batch failed:', e)
                failed += len(batch)

        cur_dest.close()
        try:
            conn_dest.close()
        except Exception:
            pass

        conn.close()
        print(f'Migration complete. success={success} failed={failed}')
        return

    # Fallback to per-row insert using storage.insert
    success = 0
    failed = 0
    for r in rows:
        _, ts, temperature, humidity, wind_speed, wind_dir, barometer, rain_rate, solar_rad, uv, ac_solar_w, house_power_w, net_balance = r
        ts_norm = normalize_timestamp(ts)
        record = {
            'timestamp': ts_norm,
            'temperature': temperature,
            'humidity': humidity,
            'wind_speed': wind_speed,
            'wind_dir': wind_dir,
            'barometer': barometer,
            'rain_rate': rain_rate,
            'solar_rad': solar_rad,
            'uv': uv,
            'ac_solar_w': ac_solar_w,
            'house_power_w': house_power_w,
            'net_balance': net_balance,
        }
        try:
            ok = storage.insert(record)
            if ok:
                success += 1
            else:
                failed += 1
        except Exception as e:
            print('Insert failed for id', r[0], e)
            failed += 1

    conn.close()
    print(f'Migration complete. success={success} failed={failed}')


if __name__ == '__main__':
    # look for telemetry.db in current dir or data/telemetry.db
    candidates = ['telemetry.db', 'data/telemetry.db', './telemetry.db']
    found = None
    for c in candidates:
        if Path(c).exists():
            found = c
            break
    if not found:
        print('No local telemetry.db found. If running in docker, copy it out:')
        print('  docker cp ecopi-dashboard:/data/telemetry.db ./telemetry.db')
    else:
        print('Using SQLite DB at', found)
        migrate(found)
